// Note that names *cannot* use underscores, but *can* use dashes
// (In Rust the dashes are converted to underscores, as usual)
// They also can't use numeric digits for some reason!

package acme:plugins@1.0.0;

// This is what the host will expose to our plugins
interface host {
    log: func(message: string);
}

// This is what our plugins will expose to the host
interface prettify-plugin {
    prettify: func(content: string) -> result<string, string>;

    prettify-words: func(content: list-resource) -> result<string, string>;

    resource list-resource {
        constructor(items: list<string>);
        get: func() -> list<string>;
        length: func() -> u64;
    }
}

// We can create additional worlds per plugin type
// You can import/export more than one interface
// (as well as individual functions, types, and resources)
world prettify {
    import host;
    export prettify-plugin;
}
