// Note that names *cannot* use underscores, but *can* use dashes
// (In Rust the dashes are converted to underscores, as usual)
// They also can't use numeric digits for some reason!

package acme:plugins@1.0.0;

// This is what the host will expose to our plugins

interface host {
    log: func(message: string);

    log-structured: func(message: string, properties: map-resource);

    // WIT doesn't have a map type, but we can implement it as a resource

    // Note the "take()" function --
    // It is my personal practice to provide such a function (when it makes sense)
    // that can move out all the resource's internal data at once

    resource map-resource {
        constructor(key-value-pairs: list<tuple<string, string>>);
        take: func() -> list<tuple<string, string>>;
        length: func() -> u64;
    }
}

// This is what our plugins will expose to the host

interface prettify-plugin {
    prettify: func(words: list<string>) -> result<string, string>;

    greet: func(person: person-resource) -> result<string, string>;

    // This resource isn't very interesting; it's just an example

    // Note that exported resources do not use "&mut self",
    // so we cannot trivially implement a "take()" function
    // (we'd have to use Cell, RefCell or similar)

    // What we can do easily is clone the resource's internal data
    // My practice is to call this function "replica()"

    resource person-resource {
        constructor(first-name: string, last-name: string);
        replica: func() -> tuple<string, string>;
    }
}

// We can create additional worlds per plugin type
// You can import/export more than one interface
// (as well as individual functions, types, and resources)

world prettify {
    import host;
    export prettify-plugin;
}
